# Generated by Django 3.1 on 2020-08-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=4000)),
                ('url', models.CharField(max_length=4000)),
                ('timestamp', models.DateTimeField()),
                ('response_status', models.IntegerField()),
                ('response_time', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
            options={
                'index_together': {('title', 'timestamp')},
            },
        ),
    ]
